### ISSUE TITLE
Deprecate <NamedDimensionalType> ?

### ISSUE THREAD

**Issue by borismarin** [LEMS/jLEMS#56]
The only Element from the previous list (#55) that is not used in the NeuroML2 schamata (dev branch) is `<NamedDimensionalType>`. Candidate for deprecation?

**Comment by pgleeson** [comment]
`<NamedDimensionalType>` is in the schema, but it is never used as a standalone element inside a `<Lems>` element. It just there to be extended by other elements like `<Parameter>` and  `<Exposure>` which all have the same attributes. So it can't be deprecated from Lems since it's not realy in Lems...

**Comment by robertcannon** [comment]
Lets just delete it from the Schema. One down :)

**Comment by borismarin** [comment]
Done!

**Comment by borismarin** [comment]
On a second thought, I am keeping it in the schema but marking it as abstract.
