### ISSUE TITLE
<Child> <Children> rationale

### ISSUE THREAD

**Issue by borismarin** [LEMS/jLEMS#61]
Is the `<Child> <Children>` distinction used only for purposes of structure validation, i.e. when a Component is instantiated, it _must_ have _only one_ subcomponent of the type specified in `<Child>`, but _can_ have _a number_ of subelement whose type is defined in `<Children>`? What are the advantages of that over having only `<Children>` with (optional?) "max" or "min" attributes, similarly to what is done for xsd?

**Comment by borismarin** [comment]
I see that in the jld, there are `childHM, childrenHM, componentHM`. Isn't that trichotomy related to the fact that in the end `Child, Children` are equally treated down the pipeline?

**Comment by robertcannon** [comment]
Yes, you could have only Children and have 
Children max=1 min=1 where we use child.

The advantage would be one less element. The disadvantage would be that it generates an exception in my internal (mental I mean) parser in that a plural noun which has only one element is  a logical impossibility :)   

If you think of java inheritance, instead of having one class that you make do different things by setting particular parameter values  it is generally better to subclass it for the different variants so you put the semantics in the class structure which makes it more explicit to the reader and gives you a placeholder to implement the different logic that the separate cases may require rather than having lots of "if max ==1 then..." type stuff.

So,  then the question is whether Child and Children are sufficiently different in the way they are used when expressing models to justify this or whether one is just a minor variant of the other.

I tend to think they are, for example with a HHTransition which requires exactly one Child for the forward rate and one for the reverse rate. This is copnceptually quite different from a channel which has gates as children and could have 0 or 10 without causing any problems.

**Comment by borismarin** [comment]
Agreed.
